name: Update GIF Only

on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures
  workflow_dispatch:

jobs:
  update-gif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch top GIF and update section
        env:
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
          GIPHY_NAME_CAT: ${{ vars.GIPHY_NAME_CAT }}
        run: |
          # Sélection aléatoire d'une catégorie
          IFS=',' read -r -a CATEGORIES <<< "$GIPHY_NAME_CAT"
          RANDOM_CATEGORY=${CATEGORIES[$RANDOM % ${#CATEGORIES[@]}]}
          echo "Selected category: $RANDOM_CATEGORY"

          # Requête à l'API Giphy
          RESPONSE=$(curl -s "https://api.giphy.com/v1/gifs/search?api_key=$GIPHY_API_KEY&q=$RANDOM_CATEGORY&limit=10&rating=g&lang=en")

          # Récupérer une URL de GIF aléatoire dans les résultats
          COUNT=$(echo "$RESPONSE" | jq '.data | length')
          if [ "$COUNT" -eq 0 ]; then
            echo "❌ Aucun GIF trouvé pour la catégorie $RANDOM_CATEGORY"
            exit 1
          fi

          INDEX=$((RANDOM % COUNT))
          GIF_URL=$(echo "$RESPONSE" | jq -r ".data[$INDEX].images.original.url" | sed 's/\?.*$//')

          echo "GIF URL sélectionnée : $GIF_URL"

          # Créer le contenu du GIF sans les balises (juste la ligne markdown)
          echo "![Trending GIF]($GIF_URL)" > new_gif_content.md

          # Remplacer la section GIF dans README.md en gardant les balises
          sed -i '/<!-- GIF_SECTION -->/,/<!-- END_GIF_SECTION -->/{
            /<!-- GIF_SECTION -->/{p; r new_gif_content.md
            }
            /<!-- GIF_SECTION -->/!{/<!-- END_GIF_SECTION -->/!d}
          }' README.md

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add README.md
            git commit -m "Update GIF only"
            git push
          fi
